remote_theme: LeakyAbstractions/pretty-docs
url: https://connectustoday.github.io
baseurl: /docs
title: &site_title ConnectUS Docs
description: &site_description Documentation for ConnectUS.today
branding:
  icon:
    name: icon_documents_alt
  highlight: ConnectUS
  bold: Docs
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: ConnectUS
  copyright:
    notice: 
    author: "[connectus.today](https://connectus.today)"


#
# Social
#
open_graph:
  title: *site_title
  site_name: *site_title
  description: *site_description
  locale: en_US
  image: /assets/images/thumb.png
twitter_cards:
  title: *site_title
  description: *site_description
  creator: *site_owner_twitter
  card: summary_large_image
  image: /assets/images/thumb.png
share:
  github:
    repo: connectustoday/api-server
    position: right
    color: red


# Google Analytics
google_analytics: UA-61670496-5


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
